Feature/challenges
SnakeTechProject/snaketech-frontend pull request #10
Opened 2022-09-16 22:36 UTC by marcosantoniosantana

2022-09-16 22:46 UTC, viniciuscosmome submitted a review, later dismissed

2022-09-17 14:04 UTC, dansenpir requested changes

2022-09-17 14:04 UTC, dansenpir commented on src/components/Challenge/challenge.module.scss
> +    margin-top: 69px;
@marcosantoniosantana Seria interessante não duplicar as tags ul e li, seguindo apenas dessa forma:

ul {
  li {
  }
}

2022-09-17 14:04 UTC, dansenpir commented on src/components/Challenge/challenge.module.scss
> +  /*top: 160px;*/
@marcosantoniosantana Não é uma boa prática manter código comentado nos commits.

2022-09-18 14:45 UTC, dansenpir approved these changes

2022-09-18 14:46 UTC, viniciuscosmome approved these changes

2022-09-18 14:47 UTC, merged