Feature/news jobs views create
SnakeTechProject/snaketech-frontend pull request #11
Opened 2022-09-18 22:27 UTC by VMatiasDev

What this PR includes:

* Adds images that will be used on news (until this moment)
* Adds proptypes on blogcards component
* Create news cards component
* Create jobs cards component
* Create topviews cards component
* Import everything to homepage (organization on the page is missing)

2022-09-18 22:57 UTC, viniciuscosmome requested changes

2022-09-18 22:57 UTC, viniciuscosmome commented on src/pages/Home/index.jsx
>        <div className={styles.cardsBlogContainer}>
@VMatiasDev 
Verifica esse fundo branco do container, ele deve cobrir a tela inteira horizontalmente.
<br />

![image](https://user-images.githubusercontent.com/48590313/190931510-a42f1694-faa6-489d-86ad-933d3d65ab39.png)

2022-09-19 21:36 UTC, MullerHub submitted a review, later dismissed
it's good

2022-09-19 22:28 UTC, dansenpir submitted a review, later dismissed
LGTM

2022-09-20 01:16 UTC, viniciuscosmome approved these changes

2022-09-20 11:56 UTC, M0nicaVaz commented
LGTM

2022-09-20 11:57 UTC, M0nicaVaz approved these changes

2022-09-20 16:37 UTC, merged